#!/usr/bin/env python3
"""Generate original 8x8 UI pictograms as unfiltered 1-bpp LVGL fonts.
No external font, rasterizer or build-time dependency is required.
"""
from pathlib import Path
import re

# Rows are bit masks, most significant bit at the left. MIT, like main/.
ICONS = {
 'AUDIO': '1e 12 12 12 72 f2 e6 0c',
 'BACKSPACE': '00 3f 41 95 89 95 41 3f',
 'BATTERY_FULL': '00 7e db db db db 7e 00',
 'CLOSE': '00 42 24 18 18 24 42 00',
 'DIRECTORY': '00 70 88 ff 81 81 81 ff',
 'DOWN': '00 00 42 24 18 00 00 00',
 'DOWNLOAD': '18 18 18 5a 3c 18 81 ff',
 'EDIT': '03 07 0e 1c 38 70 e0 c0',
 'EYE_CLOSE': '80 46 29 11 28 44 82 01',
 'FILE': '78 4c 46 7e 42 42 42 7e',
 'IMAGE': 'ff 81 a1 85 8d b9 f1 ff',
 'KEYBOARD': '00 ff 81 d5 ab 81 bd ff',
 'LEFT': '00 08 10 20 10 08 00 00',
 'LIST': '00 df 00 df 00 df 00 00',
 'MINUS': '00 00 00 7e 00 00 00 00',
 'NEW_LINE': '02 02 12 22 7e 20 10 00',
 'NEXT': '00 42 62 72 7a 72 62 42',
 'OK': '00 01 02 44 28 10 00 00',
 'PASTE': '3c 66 c3 db c3 db c3 ff',
 'PAUSE': '00 66 66 66 66 66 66 00',
 'PLAY': '00 40 60 70 78 70 60 40',
 'PLUS': '00 18 18 7e 18 18 00 00',
 'PREV': '00 42 46 4e 5e 4e 46 42',
 'REFRESH': '3a 46 82 00 00 41 62 5c',
 'RIGHT': '00 20 10 08 10 20 00 00',
 'SAVE': 'fe 92 92 9e 82 ba ba fe',
 'SETTINGS': '18 5a 7e e7 e7 7e 5a 18',
 'STOP': '00 7e 7e 7e 7e 7e 7e 00',
 'TRASH': '18 7e 00 42 5a 5a 42 7e',
 'UP': '00 00 18 24 42 00 00 00',
 'UPLOAD': '18 3c 5a 18 18 18 81 ff',
 'USB': '18 3c 18 5a 5a 3c 18 18',
 'VOLUME_MAX': '10 32 74 f5 f5 74 32 10',
 'WARNING': '18 24 24 5a 5a 42 99 ff',
 'WIFI': '00 7e 81 3c 42 18 00 18',
}
root = Path(__file__).resolve().parents[1]
def generate():
    symbols = (root/'managed_components/lvgl__lvgl/include/lvgl/font/lv_symbol_def.h').read_text()
    cps = {name: bytes.fromhex(raw.replace('\\x', '')).decode('utf8')
           for name, raw in re.findall(r'#define LV_SYMBOL_(\w+)\s+"([^"]+)"', symbols) if '\\x' in raw}
    entries = sorted((ord(cps[k]), k, bytes.fromhex(v)) for k,v in ICONS.items())
    for scale in (2,4):
        side = 8*scale
        name = f'font_icons{side}'
        bitmap=[]; descriptors=['    {0},']
        for cp,key,rows in entries:
            offset=len(bitmap)
            for row in rows:
                bits=''.join(('1' if row & (128>>x) else '0')*scale for x in range(8))
                packed=[int(bits[i:i+8],2) for i in range(0,len(bits),8)]
                bitmap.extend(packed*scale)
            descriptors.append(f'    {{.bitmap_index={offset}, .adv_w={(side+4)*16}, .box_w={side}, .box_h={side}, .ofs_x=0, .ofs_y=0}}, /* {key} */')
        start=entries[0][0]
        data=',\n'.join('    '+','.join(f'0x{x:02x}' for x in bitmap[i:i+16]) for i in range(0,len(bitmap),16))
        offsets=','.join(str(cp-start) for cp,_,_ in entries)
        out=f'''/* Generated by tools/gen_ui_icons.py. Original MIT pixel pictograms. */
#include "lvgl.h"
static const uint8_t bitmap[] = {{\n{data}\n}};
static const lv_font_fmt_txt_glyph_dsc_t glyphs[] = {{\n{chr(10).join(descriptors)}\n}};
static const uint16_t unicode_list[] = {{{offsets}}};
static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{.range_start={start}, .range_length={entries[-1][0]-start+1}, .glyph_id_start=1,
      .unicode_list=unicode_list, .list_length={len(entries)}, .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY}}
}};
static const lv_font_fmt_txt_dsc_t dsc = {{
    .glyph_bitmap=bitmap, .glyph_dsc=glyphs, .cmaps=cmaps, .cmap_num=1, .bpp=1
}};
const lv_font_t {name} = {{
    .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,
    .line_height={side+4}, .base_line=2, .dsc=&dsc
}};
'''
        (root/f'main/fonts/{name}.c').write_text(out)
if __name__ == '__main__': generate()
